### ISSUE TITLE
error on startup 1.14.4

### ISSUE THREAD

**Issue by Yonk316** [Tfarcenim/RandomEnchantments#19]
[27Oct2019 12:30:35.134] [modloading-worker-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: randomenchants, class com.tfar.randomenchants.RandomEnchants
java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_51]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_51]
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_51]
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:69) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:112) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$3(AutomaticEventSubscriber.java:70) ~[?:?]
	at net.minecraftforge.fml.AutomaticEventSubscriber$$Lambda$2186/671971456.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51]
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:57) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:141) [?:28.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2075/677143503.accept(Unknown Source) [?:28.1]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2074/237492603.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2074/237492603.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2159/1341760259.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:103) ~[modlauncher-4.1.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 29 more
[debug.log](https://github.com/Tfarcenim/RandomEnchantments/files/3776130/debug.log)
[latest.log](https://github.com/Tfarcenim/RandomEnchantments/files/3776132/latest.log)

**Comment by Alpvax** [comment]
https://github.com/Tfarcenim/RandomEnchantments/blob/b4ca1a97c05164455ae50fa0d1626366839d13d4/src/main/java/com/tfar/randomenchants/util/EventHandler.java#L18
TickEvent has been moved to package net.minecraftforge.event

**Comment by Tfarcenim** [comment]
Yeah, I know how to fix it, I just haven't bothered to because 1.14 broke my favorite enchants

**Comment by Tfarcenim** [comment]
I'm not even sure if I want to maintain this mod given that https://www.curseforge.com/minecraft/mc-mods/ensorcellation now exists, as this mod is much more difficult to port and maintain than my other stuff, has gotten much more irritating to setup configuration for, and will always be niche compared to my more popular stuff.

I will revisit the mod whenever something happens to https://github.com/MinecraftForge/MinecraftForge/pull/5871, until then I have other things to do

**Comment by Tfarcenim** [comment]
screw it, added a coremod and finished porting the missing enchants
